# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: KristjanHS.TranscribeOffline
PackageVersion: 0.2.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: transcribe-offline-v0.2.6\Transcribe-Setup.exe
  PortableCommandAlias: transcribe-offline-setup
MinimumOSVersion: 10.0.17134.0
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/KristjanHS/transcribe-offline/releases/download/v0.2.6/transcribe-offline-v0.2.6.zip
  InstallerSha256: F9B47DB681FE703443831232FFCA864FDAEFF7ECA59FA82D939077423D1F6FE7
ManifestType: installer
ManifestVersion: 1.12.0
